name: Django CI & FTP Deploy - sampleauthapp
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Django Tests
        run: python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      
      - name: Clean up unnecessary files
        run: |
          find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
          find . -name "*.pyc" -delete 2>/dev/null || true
          rm -rf .git .github venv .gitignore README.md 2>/dev/null || true
          echo "Files to upload:"
          find . -type f -name "*.py" -o -name "*.txt" -o -name "sampleauthdb" -o -name "*.html" | head -10
      
      - name: Create FTP script
        run: |
          cat > ftp_upload.sh << 'EOF'
          #!/bin/bash
          
          HOST="${{ secrets.FTP_SERVER }}"
          USER="${{ secrets.FTP_USERNAME }}"
          PASS="${{ secrets.FTP_PASSWORD }}"
          
          echo "Starting FTP upload..."
          
          ftp -inv $HOST << FTPEOF
          user $USER $PASS
          passive
          binary
          
          # Upload main files
          put manage.py
          put requirements.txt
          put sampleauthdb
          
          # Create and upload authapp directory
          mkdir authapp
          cd authapp
          lcd authapp
          put __init__.py
          put admin.py
          put apps.py
          put forms.py
          put models.py
          put urls.py
          put views.py
          put tests.py
          
          # Upload authapp migrations
          mkdir migrations
          cd migrations
          lcd migrations
          put __init__.py
          put 0001_initial.py
          cd ..
          lcd ..
          
          # Upload authapp templates
          mkdir templates
          cd templates
          lcd templates
          mkdir authapp
          cd authapp
          lcd authapp
          mput *.html
          cd ../..
          lcd ../..
          cd ..
          lcd ..
          
          # Create and upload sampleauthapp directory
          mkdir sampleauthapp
          cd sampleauthapp
          lcd sampleauthapp
          put __init__.py
          put asgi.py
          put settings.py
          put urls.py
          put wsgi.py
          
          pwd
          ls
          quit
          FTPEOF
          
          echo "FTP upload completed"
          EOF
          
          chmod +x ftp_upload.sh
      
      - name: Upload files via FTP
        run: ./ftp_upload.sh
