name: Django CI & FTP Deploy - sampleauthapp
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Django Tests
        run: python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      
      - name: Clean up unnecessary files
        run: |
          find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
          find . -name "*.pyc" -delete 2>/dev/null || true
          rm -rf .git .github venv .gitignore README.md 2>/dev/null || true
          echo "Files to upload:"
          find . -type f | head -10
      
      - name: Install ncftp
        run: sudo apt-get update && sudo apt-get install -y ncftp
      
      - name: Test FTP connection
        run: |
          echo "Testing FTP connection..."
          ncftpls -u ${{ secrets.FTP_USERNAME }} -p ${{ secrets.FTP_PASSWORD }} ftp://${{ secrets.FTP_SERVER }}/
      
      - name: Upload main files
        run: |
          echo "Uploading main Python files..."
          ncftpput -v -u ${{ secrets.FTP_USERNAME }} -p ${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }} ./ manage.py || true
          ncftpput -v -u ${{ secrets.FTP_USERNAME }} -p ${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }} ./ requirements.txt || true
          
      - name: Upload database
        run: |
          echo "Uploading database..."
          ncftpput -v -u ${{ secrets.FTP_USERNAME }} -p ${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }} ./ sampleauthdb || true
          
      - name: Upload authapp directory
        run: |
          echo "Uploading authapp..."
          ncftpput -R -v -u ${{ secrets.FTP_USERNAME }} -p ${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }} ./ authapp/
          
      - name: Upload sampleauthapp directory  
        run: |
          echo "Uploading sampleauthapp..."
          ncftpput -R -v -u ${{ secrets.FTP_USERNAME }} -p ${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }} ./ sampleauthapp/
          
      - name: Verify upload
        run: |
          echo "Verifying upload..."
          ncftpls -u ${{ secrets.FTP_USERNAME }} -p ${{ secrets.FTP_PASSWORD }} ftp://${{ secrets.FTP_SERVER }}/ || true
